from enum import Enum


class Position(Enum):
    PRODUCT_MANAGEMENT = "Product Management"
    DATA_ANALYST = "Data Analyst"
    DATA_SCIENCE = "Data Science, ML & Algorithms"
    SOFTWARE_ENGINEERING = "Software Engineering"
    FULLSTACK_DEVELOPMENT = "Fullstack Development"
    QA = "QA"
    CYBERSECURITY = "Cybersecurity"
    IT_AND_SYSTEM_ADMINISTRATION = "IT and System Administration"
    FRONTEND_DEVELOPMENT = "Frontend Development"
    DEV_OPS = "DevOps"
    UI_UX = "UI/UX, Design & Content"
    HR_RECRUITMENT = "HR & Recruitment"
    MOBILE_DEVELOPMENT = "Mobile Development"
    HARDWARE_ENGINEERING = "Hardware Engineering"
    EMBEDDED_ENGINEERING = "Embedded, Low Level & Firmware Engineering",
    CUSTOMER_SUCCESS = "Customer Success"
    PROJECT_MANAGEMENT = "Project Management"
    OPERATIONS = "Operations"
    FINANCE = "Finance"
    SYSTEMS_ENGINEERING = "Systems Engineering"
    MARKETING = "Marketing"
    SALES = "Sales"
    LEGAL_POLICY = "Compliance, Legal & Policy"
    C_LEVEL = "C-Level"
    BUSINESS_DEVELOPMENT = "Business Development"
    MECHANICAL_ENGINEERING = "Mechanical Engineering"
    NATURAL_SCIENCE = "Natural Science"
    OTHER = "Other"
