from enum import Enum


class GoozaliFieldChoice(Enum):
    PRODUCT_MANAGEMENT = "Product Management"
    DATA_ANALYST = "Data Analyst"
    DATA_SCIENCE_ML_ALGORITHMS = "Data Science, ML & Algorithms"
    SOFTWARE_ENGINEERING = "Software Engineering"
    QA = "QA"
    CYBERSECURITY = "Cybersecurity"
    IT_AND_SYSTEM_ADMINISTRATION = "IT and System Administration"
    FRONTEND_DEVELOPMENT = "Frontend Development"
    DEVOPS = "DevOps"
    UI_UX_DESIGN_CONTENT = "UI/UX, Design & Content"
    HR_RECRUITMENT = "HR & Recruitment"
    MOBILE_DEVELOPMENT = "Mobile Development"
    HARDWARE_ENGINEERING = "Hardware Engineering"
    EMBEDDED_LOW_LEVEL_FIRMWARE_ENGINEERING = "Embedded, Low Level & Firmware Engineering"
    CUSTOMER_SUCCESS = "Customer Success"
    PROJECT_MANAGEMENT = "Project Management"
    OPERATIONS = "Operations"
    FINANCE = "Finance"
    SYSTEMS_ENGINEERING = "Systems Engineering"
    MARKETING = "Marketing"
    SALES = "Sales"
    COMPLIANCE_LEGAL_POLICY = "Compliance, Legal & Policy"
    C_LEVEL = "C-Level"
    BUSINESS_DEVELOPMENT = "Business Development"
    MECHANICAL_ENGINEERING = "Mechanical Engineering"
    NATURAL_SCIENCE = "Natural Science"
    OTHER = "Other"
